### ISSUE TITLE
Something's not right.

### ISSUE THREAD

**Issue by myxibrium** [gyv-media/pychargify#2]
The very last line of api.py seems to be wrong. It currently says this:
return ChargifyPostBack(self.api_key, self.sub_domain)
And it should say this:
return ChargifyPostBack(self.api_key, self.sub_domain, postbackdata)

Otherwise, why would postbackdata be given as an argument of that class factory? (to be honest I'm not even sure what a PostBack is quite yet, I'm still pretty newbie at this)

**Comment by ghost** [comment]
Correct, fixed.

PostBack handles the postback data when chargify posts back to you application to say a sucscription has changed.
