### ISSUE TITLE
Issues initializing Chargify()

### ISSUE THREAD

**Issue by Lukich** [gyv-media/pychargify#6]
So, per instructions I was trying to initialize Chargify with api key and subdomain.  However, it was failing, telling me that I need to specify api key and subdomain.  Further investigation led me to line 617 in api.py.  Basically, right now it looks for self.api_key and self.subdomain, which are defined as empty, so the code gets ignored.  Switching them to apikey and subdomain fixed this issue.  Out of curiosity - is this app used by anyone?  I'm surprised no one commented on this.

**Comment by ghost** [comment]
After I wrote the code a few years ago we decided not to use Chargify, so the library is here incase its of use to others rather than being trashed. It gets the odd pull request but as I have no way to test them and i just blindly merge them.

**Comment by Lukich** [comment]
I see.  Thanks!
